# User config
author: "Junzhe Wu"
tagline: "Personal Website"
description: "Master's student @ University of Michigan."
research: "Robot Perception, SLAM."
keywords: "Robotics,Computer Vision,Deep Learning"
email: "junzhewu@umich.edu"
linkedin: "https://www.linkedin.com/in/junzhewu/"
github: "https://github.com/tccoin"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed