# User config
author: "Junzhe Wu"
tagline: "Junzhe Wu Personal Website"
description: "Master's student @ University of Michigan.<br> Expected graduation date: Apr 2023."
research: "Robotics, Computer Vision, Deep Learning."
keywords: "Robotics,Computer Vision,Deep Learning"
email: "junzhewu@umich.edu"
linkedin: "https://www.linkedin.com/in/junzhewu/"
github: "https://github.com/tccoin"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed